/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Time = IDL.Int;
export const ProductInterest = IDL.Record({
  'hennaPowder' : IDL.Bool,
  'multaniMitti' : IDL.Bool,
});
export const Inquiry = IDL.Record({
  'country' : IDL.Text,
  'name' : IDL.Text,
  'company' : IDL.Text,
  'message' : IDL.Text,
  'timestamp' : Time,
  'products' : ProductInterest,
});

export const idlService = IDL.Service({
  'countProductInterest' : IDL.Func([], [IDL.Nat, IDL.Nat], ['query']),
  'getAllInquiries' : IDL.Func([], [IDL.Vec(Inquiry)], ['query']),
  'getInquiriesByCountry' : IDL.Func([IDL.Text], [IDL.Vec(Inquiry)], ['query']),
  'getInquiryByTimestamp' : IDL.Func([Time], [Inquiry], ['query']),
  'submitInquiry' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Bool, IDL.Bool, IDL.Text],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Time = IDL.Int;
  const ProductInterest = IDL.Record({
    'hennaPowder' : IDL.Bool,
    'multaniMitti' : IDL.Bool,
  });
  const Inquiry = IDL.Record({
    'country' : IDL.Text,
    'name' : IDL.Text,
    'company' : IDL.Text,
    'message' : IDL.Text,
    'timestamp' : Time,
    'products' : ProductInterest,
  });
  
  return IDL.Service({
    'countProductInterest' : IDL.Func([], [IDL.Nat, IDL.Nat], ['query']),
    'getAllInquiries' : IDL.Func([], [IDL.Vec(Inquiry)], ['query']),
    'getInquiriesByCountry' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Inquiry)],
        ['query'],
      ),
    'getInquiryByTimestamp' : IDL.Func([Time], [Inquiry], ['query']),
    'submitInquiry' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Bool, IDL.Bool, IDL.Text],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };